/* AUTO-GENERATED from catalog.csv by tools/build-catalog.mjs — DO NOT EDIT BY HAND.
   101 activities. Regenerate with: node tools/build-catalog.mjs */
window.NTL_CATALOG = [
  {
    "order": 1,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "sea",
    "categoriaLabel": "Sea Experience",
    "titulo": "Sunset Sailboat Trip with Open Bar & Snacks",
    "descripcion": "Relax on a luxury yacht along the Barcelona coastline at sunset. Enjoy unlimited drinks, fresh snacks, and a swim in the Mediterranean.",
    "precio": 45,
    "precioDisplay": "45€ - 55€",
    "rating": 4.9,
    "trending": true,
    "keywords": "sunset sailboat trip open bar snacks yacht sea boat",
    "etiquetaPie": "Small Group",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-2-hour-sunset-sailboat-trip-t173643/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/6c830d66ed2b49a95dca0aa7b01a23ec4f076e69af30622628026dfb4ba8d346.png/99.jpg"
  },
  {
    "order": 2,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Sagrada Familia: Skip-the-Line Ticket",
    "descripcion": "Bypass the notoriously long lines and explore Gaudí's unfinished masterpiece at your own pace with a multi-language audio guide.",
    "precio": 49,
    "precioDisplay": "30€ - 38€",
    "rating": 4.8,
    "trending": false,
    "keywords": "sagrada familia skip the line ticket audio guide fast track",
    "etiquetaPie": "Fast Track",
    "url": "https://www.getyourguide.com/barcelona-l45/sagrada-familia-skip-the-line-ticket-t50027/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/62bacf6a87bba.jpeg/99.jpg"
  },
  {
    "order": 3,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Guided Tour",
    "titulo": "Sagrada Familia: Guided Tour + Tower",
    "descripcion": "Discover the hidden symbolism of the Sagrada Familia with an expert local guide and climb the towers for panoramic city views.",
    "precio": 34,
    "precioDisplay": "60€ - 75€",
    "rating": 4.7,
    "trending": false,
    "keywords": "sagrada familia guided tour tower access architecture",
    "etiquetaPie": "Expert Guide",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-sagrada-familia-tour-optional-tower-visit-t72879/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/590354fed56f6.jpeg/99.jpg"
  },
  {
    "order": 4,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Guided Tour",
    "titulo": "Sagrada Familia: Skip-the-Line & Guided Tour",
    "descripcion": "Enjoy priority access and a comprehensive guided tour of the basilica, learning about Gaudí's inspirations.",
    "precio": 65,
    "precioDisplay": "45€ - 55€",
    "rating": 4.8,
    "trending": false,
    "keywords": "sagrada familia skip the line entry ticket tour",
    "etiquetaPie": "Fast Track",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-sagrada-familia-skip-the-line-entry-ticket-tour-t288805/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/448290a706817776.jpeg/99.jpg"
  },
  {
    "order": 5,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Park Güell: Skip-the-Line Entry",
    "descripcion": "Skip the line to explore Gaudí's famous monumental zone and gardens overlooking the beautiful city of Barcelona.",
    "precio": 49,
    "precioDisplay": "10€ - 15€",
    "rating": 4.6,
    "trending": false,
    "keywords": "park guell entrance ticket skip the line",
    "etiquetaPie": "Top Rated",
    "url": "https://www.getyourguide.com/barcelona-l45/skip-the-line-park-guell-entrance-ticket-t53791/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/93473fd2896a1e0e.jpeg/99.jpg"
  },
  {
    "order": 6,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "City Tour",
    "titulo": "Hop-on Hop-off Bus Tour",
    "descripcion": "Discover the city at your own pace with 24 or 48-hour access to open-top buses covering all major landmarks.",
    "precio": 13,
    "precioDisplay": "30€ - 35€",
    "rating": 4.5,
    "trending": false,
    "keywords": "hop on hop off bus tour 24 48 hour",
    "etiquetaPie": "Flexible",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-24-or-48-hour-hop-on-hop-off-bus-tour-t1225/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5e171de5001c0983e952afec01e3c681c9ff5e451f649d366f14be8452a7ce09.jpg/99.jpg"
  },
  {
    "order": 7,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "sea",
    "categoriaLabel": "Water Sports",
    "titulo": "Jet Ski Rental (No License Needed)",
    "descripcion": "Experience the thrill of riding a jetski along the beautiful Barcelona coastline. Safe, fun, and no license required.",
    "precio": 34,
    "precioDisplay": "85€ - 110€",
    "rating": 4.8,
    "trending": false,
    "keywords": "jet ski rental without license",
    "etiquetaPie": "Action",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-jet-ski-rental-without-a-license-30-minutes-60-minutes-t1012539/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/651098ced076b3cca4cb135a512583334c9ff251b30f66bb81afd7f25b0673a2.jpeg/99.jpg"
  },
  {
    "order": 8,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Casa Batlló: 10D Experience",
    "descripcion": "Immerse yourself in Gaudí's magical world with a spectacular 10D augmented reality self-audioguide tour.",
    "precio": 95,
    "precioDisplay": "35€ - 45€",
    "rating": 4.8,
    "trending": false,
    "keywords": "casa batllo 10d experience self audioguide",
    "etiquetaPie": "Immersive",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-casa-batllo-10d-experience-t398519/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/aa3ab6c4aaa9cc0c.jpeg/99.jpg"
  },
  {
    "order": 9,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Day Trip",
    "titulo": "Costa Brava Day Tour with Lunch",
    "descripcion": "Escape the city for a full day of pristine beaches, picturesque coastal towns, and a delicious traditional lunch.",
    "precio": 35,
    "precioDisplay": "85€ - 95€",
    "rating": 4.7,
    "trending": false,
    "keywords": "costa brava day tour lunch",
    "etiquetaPie": "Full Day",
    "url": "https://www.getyourguide.com/barcelona-l45/discover-the-costa-brava-from-barcelona-t56179/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/62d10aa996e20.jpeg/99.jpg"
  },
  {
    "order": 10,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Active Tour",
    "titulo": "Historical Bike or E-Bike Tour",
    "descripcion": "Cruise through historic neighborhoods and hidden gems on a comfortable bike or e-bike with a local guide.",
    "precio": 89,
    "precioDisplay": "25€ - 35€",
    "rating": 4.6,
    "trending": false,
    "keywords": "bike e-bike historical tour",
    "etiquetaPie": "Eco-friendly",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-25-hour-bike-or-e-bike-historical-tour-t99678/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/b3df3f1f0d404add56cb7eab2a90ab48338ed603d9e4b98ab8bcd26d9d8bf68b.jpeg/99.jpg"
  },
  {
    "order": 11,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Day Trip",
    "titulo": "3 Countries Trip: Andorra, France & Spain",
    "descripcion": "Visit three countries in one epic day! Explore the Pyrenees mountains, thermal springs, and charming villages.",
    "precio": 29,
    "precioDisplay": "130€ - 150€",
    "rating": 4.8,
    "trending": false,
    "keywords": "guided day trip andorra france spain",
    "etiquetaPie": "Full Day",
    "url": "https://www.getyourguide.com/barcelona-l45/from-barcelona-guided-day-trip-to-andorra-france-and-spain-t436024/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/db19d7fe1131c1ca4bea64a4089d0e2128f2662792a9add5554ac7c399e1fa0d.jpg/99.jpg"
  },
  {
    "order": 12,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Nightlife & Show",
    "titulo": "Flamenco Show at Palau Dalmases",
    "descripcion": "Experience the raw passion of authentic Spanish Flamenco inside a stunning 17th-century Gothic palace.",
    "precio": 140,
    "precioDisplay": "30€ - 38€",
    "rating": 4.8,
    "trending": false,
    "keywords": "flamenco show palau dalmases",
    "etiquetaPie": "Live Music",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-flamenco-show-at-palau-dalmases-t405115/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/afbdf8a8adeda43b4d738fca5f4a8124c9415c1332700dcdd8e8a786830ff237.jpg/99.jpg"
  },
  {
    "order": 13,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "sea",
    "categoriaLabel": "Sea Experience",
    "titulo": "Sunset Sail, Tapas & Live Music",
    "descripcion": "Enjoy the Mediterranean breeze with premium tapas, live music, and cold drinks on a gorgeous sailboat.",
    "precio": 30,
    "precioDisplay": "70€ - 85€",
    "rating": 4.8,
    "trending": false,
    "keywords": "sunset sailing tour tapas music dinner",
    "etiquetaPie": "Romantic",
    "url": "https://www.getyourguide.com/barcelona-l45/2-hour-sunset-sailing-tour-of-barcelona-from-port-vell-t108412/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5c7fab43c09ec.jpeg/99.jpg"
  },
  {
    "order": 14,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Tours & Views",
    "titulo": "Montjuïc Cable Car Roundtrip",
    "descripcion": "Soar above the city and enjoy stunning panoramic views from the iconic Montjuïc hill.",
    "precio": 75,
    "precioDisplay": "15€ - 18€",
    "rating": 4.6,
    "trending": false,
    "keywords": "montjuic cable car roundtrip ticket views",
    "etiquetaPie": "Scenic",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-montjuic-cable-car-roundtrip-ticket-t23477/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/546ccc9797ca7.jpeg/99.jpg"
  },
  {
    "order": 15,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Museum",
    "titulo": "FC Barcelona Museum: Barça Immersive Tour",
    "descripcion": "Dive into Barça's glorious history and feel the stadium's magic in this state-of-the-art immersive exhibition.",
    "precio": 16,
    "precioDisplay": "28€ - 35€",
    "rating": 4.7,
    "trending": false,
    "keywords": "fc barcelona museum barca immersive tour ticket",
    "etiquetaPie": "Sports",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-barca-immersive-exhibition-ticket-t449261/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/6482d923576aa.jpeg/99.jpg"
  },
  {
    "order": 16,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "sea",
    "categoriaLabel": "Water Sports",
    "titulo": "Costa Brava: Kayak, Snorkel & Cliff Jump",
    "descripcion": "Paddle through crystal-clear waters, explore hidden sea caves, and cliff jump in the beautiful Costa Brava.",
    "precio": 28,
    "precioDisplay": "60€ - 70€",
    "rating": 4.9,
    "trending": false,
    "keywords": "kayaking snorkeling costa brava cliff jump",
    "etiquetaPie": "Adventure",
    "url": "https://www.getyourguide.com/barcelona-l45/from-barcelona-kayaking-snorkeling-in-la-costa-brava-t119389/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/640f0704d14b6.png/99.jpg"
  },
  {
    "order": 17,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food Tour",
    "titulo": "Tapas Walking Tour with Wine & Vermouth",
    "descripcion": "Savor authentic local flavors, exquisite wines, and vermouth while exploring Barcelona's historic streets.",
    "precio": 65,
    "precioDisplay": "80€ - 95€",
    "rating": 4.9,
    "trending": false,
    "keywords": "food tasting tour tapas wine vermouth",
    "etiquetaPie": "Gastronomy",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-food-tasting-tour-tapas-wine-and-vermouth-t303593/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/62e6830d10ceb.jpeg/99.jpg"
  },
  {
    "order": 18,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Day Trip",
    "titulo": "Montserrat, Cogwheel & Winery Tour",
    "descripcion": "Visit the breathtaking Montserrat mountains, see the famous Black Madonna, and taste exquisite local wines.",
    "precio": 85,
    "precioDisplay": "60€ - 75€",
    "rating": 4.8,
    "trending": false,
    "keywords": "montserrat cogwheel black madonna winery tour",
    "etiquetaPie": "Culture & Wine",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-montserrat-tour-with-optional-winelunch-t382639/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3be29c404103f00b.jpeg/99.jpg"
  },
  {
    "order": 19,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food Tour",
    "titulo": "Paella Cooking & Boqueria Market Tour",
    "descripcion": "Cook authentic paella and explore the famous La Boqueria market with a local chef in a hands-on culinary experience.",
    "precio": 79,
    "precioDisplay": "75€ - 89€",
    "rating": 4.9,
    "trending": false,
    "keywords": "paella cooking experience boqueria market tour food chef",
    "etiquetaPie": "Gastronomy",
    "url": "https://www.getyourguide.com/barcelona-l45/paella-cooking-experience-with-boqueria-market-tour-t44533/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5eba3f690f289dfd5604e16facd02d8d61b9f568d3bc287bb88b858575da41ef.jpeg/99.jpg"
  },
  {
    "order": 20,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "La Pedrera-Casa Milà: Ticket & Audio Guide",
    "descripcion": "Visit Gaudí's iconic Casa Milà with its surreal rooftop chimneys and modernist design, audio guide included.",
    "precio": 28,
    "precioDisplay": "28€ - 39€",
    "rating": 4.7,
    "trending": false,
    "keywords": "la pedrera casa mila ticket audio guide gaudi",
    "etiquetaPie": "Gaudí",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-la-pedrera-casa-mila-ticket-audio-guide-option-t913286/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/location/ee9f7cf42064d331.jpeg/99.jpg"
  },
  {
    "order": 21,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Museum",
    "titulo": "Picasso Museum: Skip-the-Line Guided Tour",
    "descripcion": "Skip the line and explore the world's most complete collection of Picasso's early works with an expert guide.",
    "precio": 39,
    "precioDisplay": "34€ - 42€",
    "rating": 4.7,
    "trending": false,
    "keywords": "picasso museum guided tour skip the line art",
    "etiquetaPie": "Art & Museum",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-skip-the-line-guided-tour-of-the-picasso-museum-t808734/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/28f59f42be297ddecdff394012e2264dd15cbc61b862555907eb065311dfa928.jpg/99.jpg"
  },
  {
    "order": 22,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Palau de la Música: Guided Tour",
    "descripcion": "Step inside the Palau de la Música Catalana, a UNESCO modernist jewel with a breathtaking stained-glass ceiling.",
    "precio": 22,
    "precioDisplay": "20€ - 25€",
    "rating": 4.8,
    "trending": false,
    "keywords": "palau de la musica guided tour modernist concert hall",
    "etiquetaPie": "Architecture",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-palau-de-la-musica-guided-tour-t41657/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/cb2b8013528313b212ef094bbcceb95523a9afcc93441616f83b434b50ae4972.jpg/99.jpg"
  },
  {
    "order": 23,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Family",
    "titulo": "Barcelona Aquarium: Entry Ticket",
    "descripcion": "Walk through an 80-metre underwater tunnel surrounded by sharks and Mediterranean marine life. Great for families.",
    "precio": 25,
    "precioDisplay": "24€ - 28€",
    "rating": 4.5,
    "trending": false,
    "keywords": "barcelona aquarium entry ticket sharks family kids",
    "etiquetaPie": "Family",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-aquarium-entry-ticket-t61515/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/086f74df2002c7a9.jpeg/99.jpg"
  },
  {
    "order": 24,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Air Tour",
    "titulo": "Barcelona Helicopter Tour",
    "descripcion": "See Barcelona like never before on a thrilling helicopter flight over the coastline, the port and the city's landmarks.",
    "precio": 125,
    "precioDisplay": "120€ - 150€",
    "rating": 4.8,
    "trending": false,
    "keywords": "helicopter tour aerial flight skyline adventure",
    "etiquetaPie": "Premium",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-helicopter-tour-with-local-guide-t603564/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/e13898af69eba0b2244759d8f1ec4919724e3fcd9ccb150e94d08fa9f734b44d.jpg/99.jpg"
  },
  {
    "order": 25,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "tours",
    "categoriaLabel": "Theme Park",
    "titulo": "PortAventura, Ferrari Land & Caribe",
    "descripcion": "Entry to PortAventura, Ferrari Land and Caribe Aquatic Park — one of Europe's top theme-park resorts near Barcelona.",
    "precio": 60,
    "precioDisplay": "55€ - 75€",
    "rating": 4.7,
    "trending": false,
    "keywords": "salou portaventura ferrari land caribe aquatic theme park roller coaster",
    "etiquetaPie": "Theme Park",
    "url": "https://www.getyourguide.com/salou-l1884/salou-entry-to-portaventura-ferrari-land-caribe-aquatic-t115369/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/2994f5ab5af5bcff775ea4f98150fb4f5a697b03488d19a6dabfbb21668af112.jpg/99.jpg"
  },
  {
    "order": 26,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Shopping Trip",
    "titulo": "La Roca Village Shopping Express",
    "descripcion": "Shop premium fashion brands at up to 60% off at the elegant La Roca Village outlet, round-trip transfers included.",
    "precio": 17,
    "precioDisplay": "15€ - 20€",
    "rating": 4.6,
    "trending": false,
    "keywords": "la roca village shopping express day trip outlet fashion",
    "etiquetaPie": "Shopping",
    "url": "https://www.getyourguide.com/barcelona-l45/from-barcelona-la-roca-village-shopping-expressr-day-trip-t425752/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/018d27de1968d1aefe8e59bf82e0e8aca991a4ca94cecca4c9f106ae76c75909.jpg/99.jpg"
  },
  {
    "order": 27,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Nightlife & Show",
    "titulo": "Vivaldi: The Four Seasons Concert",
    "descripcion": "Enjoy Vivaldi's Four Seasons performed live by a string ensemble in a stunning historic Barcelona venue.",
    "precio": 33,
    "precioDisplay": "30€ - 40€",
    "rating": 4.8,
    "trending": false,
    "keywords": "vivaldi four seasons concert classical music live show",
    "etiquetaPie": "Live Music",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-concert-a-vivaldi-the-four-seasons-and-more-t694860/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/bed359477b0111f80d6070400eed107c72d1a768caa8ac283fa671f77e05b890.jpg/99.jpg"
  },
  {
    "order": 28,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "City Tour",
    "titulo": "Private City Highlights Tuk-Tuk Tour",
    "descripcion": "Glide past Barcelona's highlights on a fun private electric tuk-tuk tour with a local guide. Perfect photo stops.",
    "precio": 39,
    "precioDisplay": "35€ - 49€",
    "rating": 4.9,
    "trending": false,
    "keywords": "private tuk tuk tour city highlights electric eco",
    "etiquetaPie": "Private",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-city-highlights-private-tuk-tuk-tour-t1043339/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/a5ad924fa7184a7a87b3bad3afc8d10ca4beae02f975f455b18f9ce528002a2f.jpg/99.jpg"
  },
  {
    "order": 29,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Walking Tour",
    "titulo": "Gothic Quarter Walking Tour (10+ Sights)",
    "descripcion": "Wander the atmospheric medieval streets of the Gothic Quarter and discover 10+ hidden landmarks with a guide.",
    "precio": 22,
    "precioDisplay": "20€ - 25€",
    "rating": 4.7,
    "trending": false,
    "keywords": "gothic quarter walking tour old town history attractions",
    "etiquetaPie": "Walking Tour",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-gothic-quarter-walking-tour-with-10-attractions-t503392/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/ff5f1f662cec5940e4c277f2f2238401f927cfa556ddeb6fa1c50b66b6207b70.jpg/99.jpg"
  },
  {
    "order": 30,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "City Tour",
    "titulo": "Essential Tour in a Vintage Electric Car",
    "descripcion": "Tour Barcelona's icons in style aboard a classic vintage electric car with a private driver-guide.",
    "precio": 89,
    "precioDisplay": "85€ - 99€",
    "rating": 4.8,
    "trending": false,
    "keywords": "vintage electric car essential tour gaudi sagrada highlights",
    "etiquetaPie": "Iconic",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-essential-tour-in-a-vintage-electric-car-t1161228/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/99bc089cb1489e9b60247bea8014450db84d564e9254c1448f467452c61d7dbf.png/99.jpg"
  },
  {
    "order": 31,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Park Güell: Guided Tour with Skip-the-Line",
    "descripcion": "Skip the line and discover the secrets of Gaudí's colourful Park Güell with an expert local guide.",
    "precio": 30,
    "precioDisplay": "28€ - 35€",
    "rating": 4.7,
    "trending": false,
    "keywords": "park guell guided tour skip the line gaudi",
    "etiquetaPie": "Top Rated",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-park-guell-guided-tour-t419045/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/ce92bfd0b52bdc20679ddecfb9d8a1172b8f6887152ca3ecc858e004d5fad601.png/99.jpg"
  },
  {
    "order": 32,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Nightlife & Show",
    "titulo": "Flamenco Show at the Theater",
    "descripcion": "Feel the passion of authentic flamenco — guitar, song and dance — in an intimate Barcelona theater.",
    "precio": 30,
    "precioDisplay": "28€ - 38€",
    "rating": 4.7,
    "trending": false,
    "keywords": "flamenco show theater live dance music",
    "etiquetaPie": "Live Show",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-flamenco-show-at-the-theater-t76003/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/8d94bb036f911af8.jpeg/99.jpg"
  },
  {
    "order": 33,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "City Tour",
    "titulo": "City Sightseeing Hop-On Hop-Off Bus",
    "descripcion": "Explore Barcelona at your own pace with 1 or 2-day hop-on hop-off open-top bus access to all top sights.",
    "precio": 33,
    "precioDisplay": "30€ - 35€",
    "rating": 4.5,
    "trending": false,
    "keywords": "city sightseeing hop on hop off bus tour 1 2 day",
    "etiquetaPie": "Flexible",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-hop-on-hop-off-tour-1-or-2-day-ticket-t4241/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/edac71d6a2dfed9d.jpeg/99.jpg"
  },
  {
    "order": 34,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Day Trip",
    "titulo": "Montserrat: Cog-Wheel Train & Black Madonna",
    "descripcion": "Ride the historic cog-wheel train to Montserrat monastery, see the Black Madonna and enjoy mountain views.",
    "precio": 55,
    "precioDisplay": "50€ - 60€",
    "rating": 4.7,
    "trending": false,
    "keywords": "montserrat cog wheel train black madonna royal basilica day trip",
    "etiquetaPie": "Day Trip",
    "url": "https://www.getyourguide.com/barcelona-l45/montserrat-royal-basilica-cog-wheel-train-from-barcelona-t1177/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/63580375c2779b096cbc8dbdfb82c3e16efd2021569cccea569462ef6f554aee.jpg/99.jpg"
  },
  {
    "order": 35,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Park Güell: Guided Tour with Fast-Track Ticket",
    "descripcion": "Skip the queue and discover Gaudí's colourful mosaic wonderland with an expert guide who brings its history to life.",
    "precio": 30,
    "precioDisplay": "30€ - 44€",
    "rating": 4.6,
    "trending": false,
    "keywords": "park guell gaudi guided tour fast track skip line mosaic",
    "etiquetaPie": "Fast Track",
    "url": "https://www.getyourguide.com/barcelona-l45/gaudi-s-park-guell-guided-tour-with-fast-track-ticket-t663776/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/12261969cccf19bd40150fb39169265536f883fe5cd60c3ea0d66b3cce57517f.jpg/99.jpg"
  },
  {
    "order": 36,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Tours & Trips",
    "titulo": "Barcelona: Old Town Private Walking Tour",
    "descripcion": "A private guide walks you through the Gothic Quarter's hidden corners, linking Barcelona's Roman past with its lively present.",
    "precio": 120,
    "precioDisplay": "from 120€",
    "rating": 4.9,
    "trending": false,
    "keywords": "old town private walking tour gothic quarter past present history guide",
    "etiquetaPie": "Private",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-private-tour-past-present-t498339/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/6fb95c622641e3e766d9c688f63b68f1514a2b9042ed2bc9eae55f35f7b3b3da.png/99.jpg"
  },
  {
    "order": 37,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "tours",
    "categoriaLabel": "Tours & Trips",
    "titulo": "Barcelona: Private City Tour by Eco Tuk-Tuk",
    "descripcion": "Zip past the icons in an open electric tuk-tuk — a fun, breezy way to see the highlights without the walking.",
    "precio": 99,
    "precioDisplay": "99€ - 150€",
    "rating": 4.7,
    "trending": false,
    "keywords": "private city tour electric eco tuk tuk sightseeing highlights",
    "etiquetaPie": "Private",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-city-tour-by-electric-tuk-tuk-t415748/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/635a38a7e0b79.jpeg/99.jpg"
  },
  {
    "order": 38,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Intimate Flamenco Show at Las Brujas",
    "descripcion": "Feel the duende up close in a tiny candle-lit club, where raw flamenco song, guitar and dance are just steps away.",
    "precio": 25,
    "precioDisplay": "25€ - 39€",
    "rating": 4.7,
    "trending": false,
    "keywords": "intimate flamenco show las brujas club live dance guitar nightlife",
    "etiquetaPie": "Live Show",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-espectaculo-de-flamenco-intimo-en-las-brujas-club-t968509/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/8868892385f7249bce89a3b2699fd84e1afc00e23a5836874848e4d831173c28.jpg/99.jpg"
  },
  {
    "order": 39,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "tours",
    "categoriaLabel": "Theme Park",
    "titulo": "PortAventura & Ferrari Land: 1–3 Day Ticket",
    "descripcion": "Europe's top theme park plus the world's only Ferrari Land — record-breaking coasters and thrills for the whole family.",
    "precio": 60,
    "precioDisplay": "60€ - 145€",
    "rating": 4.8,
    "trending": true,
    "keywords": "portaventura ferrari land theme park roller coaster salou costa daurada 1 2 3 day family",
    "etiquetaPie": "Family Favourite",
    "url": "https://www.getyourguide.com/salou-l1884/portaventura-ferrari-land-tickets-1-2-or-3-day-entry-t115174/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/83bfcf830f2191fa4e3365338a67b6b9a08e1d578b62c34b6735cba58eb8a9e9.jpg/99.jpg"
  },
  {
    "order": 40,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "sea",
    "categoriaLabel": "Water Park",
    "titulo": "PortAventura: Caribe Aquatic Park Ticket",
    "descripcion": "Cool off on tropical-themed slides, wave pools and lazy rivers at Costa Daurada's biggest water park.",
    "precio": 32,
    "precioDisplay": "32€ - 38€",
    "rating": 4.6,
    "trending": false,
    "keywords": "caribe aquatic water park portaventura slides pool salou costa daurada family summer",
    "etiquetaPie": "Family",
    "url": "https://www.getyourguide.com/salou-l1884/salou-portaventura-costa-caribe-aquatic-park-ticket-t33815/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/4358858243d9046472ec3b888998f1f23df49d971384b62ee0f0b9d4011d9462.jpg/99.jpg"
  },
  {
    "order": 41,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "tours",
    "categoriaLabel": "Day Trip",
    "titulo": "From Salou: Barcelona Full-Day Panoramic Tour",
    "descripcion": "Escape the coast for a day and see Barcelona's greatest hits, with free time to explore the city at your own pace.",
    "precio": 60,
    "precioDisplay": "60€ - 75€",
    "rating": 4.5,
    "trending": false,
    "keywords": "barcelona full day panoramic tour free time from salou day trip costa daurada",
    "etiquetaPie": "From Salou",
    "url": "https://www.getyourguide.com/salou-l1884/barcelona-full-day-panoramic-tour-with-free-time-from-salou-t225756/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5c9a07f8f2d18.jpeg/99.jpg"
  },
  {
    "order": 42,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Salou: All-Inclusive Beach Day with Driver & Lunch",
    "descripcion": "Private driver, reserved sun-loungers and a beachfront restaurant — a hassle-free day soaking up the Costa Daurada sun.",
    "precio": 89,
    "precioDisplay": "89€ - 120€",
    "rating": 4.7,
    "trending": false,
    "keywords": "all inclusive beach day salou driver transfer beach set restaurant sunbed costa daurada",
    "etiquetaPie": "All-Inclusive",
    "url": "https://www.getyourguide.com/salou-l1884/all-inclusive-beach-day-in-salou-driver-beach-set-and-restaurant-t1399334/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/c5fcb49cd3e8fe6b1288e0939e4c4c7081d15ce83fe95efc80ddea838f453638.png/99.jpg"
  },
  {
    "order": 43,
    "provincia": "tarragona",
    "city": "cambrils",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Cambrils: Premium Sunset Catamaran with Drinks",
    "descripcion": "Sail into the sunset on a spacious catamaran with Balinese beds, a swim stop and a drink in hand.",
    "precio": 55,
    "precioDisplay": "55€ - 75€",
    "rating": 4.8,
    "trending": false,
    "keywords": "cambrils premium catamaran sunset cruise drinks balinese beds sailing costa daurada",
    "etiquetaPie": "Sunset",
    "url": "https://www.getyourguide.com/cambrils-l91400/cambrils-3h-premium-catamaran-with-optional-balinese-beds-t1394594/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/8271cfe31a4353cb2cf5ba96642e8e642771475471b0f6fa7e6419789905456e.jpg/99.jpg"
  },
  {
    "order": 44,
    "provincia": "tarragona",
    "city": "cambrils",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "From Salou/Cambrils: Ultimate Speedboat Tour",
    "descripcion": "Feel the adrenaline as you race along the Costa Daurada coastline on a private high-speed boat.",
    "precio": 45,
    "precioDisplay": "45€ - 90€",
    "rating": 4.7,
    "trending": false,
    "keywords": "salou cambrils speedboat tour adrenaline coast sea fast boat costa daurada",
    "etiquetaPie": "Adrenaline",
    "url": "https://www.getyourguide.com/cambrils-l91400/from-salou-cambrils-ultimate-speedboat-experience-t170472/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/bb6f8edd26909c9f.jpeg/99.jpg"
  },
  {
    "order": 45,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "tours",
    "categoriaLabel": "Adventure",
    "titulo": "Salou: Off-Road Quad Safari with Hotel Pickup",
    "descripcion": "Kick up the dust on a guided quad adventure through the hills behind the coast — hotel pickup included.",
    "precio": 55,
    "precioDisplay": "55€ - 110€",
    "rating": 4.6,
    "trending": false,
    "keywords": "salou off road quad safari atv guided hotel pickup mountains adventure costa daurada",
    "etiquetaPie": "Adventure",
    "url": "https://www.getyourguide.com/salou-l1884/salou-off-road-guided-quad-safari-with-hotel-pickup-t400058/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/932dbf6fab1538420f8bdfc92db87cff47034aceae4d6ddcb7f2c862abd80f76.jpeg/99.jpg"
  },
  {
    "order": 46,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "sea",
    "categoriaLabel": "Adventure",
    "titulo": "Bosc Aventura Salou: Explorer Pack",
    "descripcion": "Swing, climb and zip through a treetop adventure course — outdoor fun for kids and adults alike.",
    "precio": 22,
    "precioDisplay": "22€ - 30€",
    "rating": 4.5,
    "trending": false,
    "keywords": "bosc aventura salou adventure park explorer pack zip lines ropes forest costa daurada",
    "etiquetaPie": "Outdoor",
    "url": "https://www.getyourguide.com/salou-l1884/bosc-aventura-salou-simple-pack-t379979/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/623efe530f790.jpeg/99.jpg"
  },
  {
    "order": 47,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "sea",
    "categoriaLabel": "Adventure",
    "titulo": "Salou: Bosc Aventura Zip-Lining Experience",
    "descripcion": "Fly between the trees on a network of thrilling zip-lines set in a pine forest just outside Salou.",
    "precio": 25,
    "precioDisplay": "25€ - 35€",
    "rating": 4.5,
    "trending": false,
    "keywords": "bosc aventura salou zip lining experience tyrolean forest adventure costa daurada",
    "etiquetaPie": "Outdoor",
    "url": "https://www.getyourguide.com/salou-l1884/salou-bosc-aventura-salou-zip-lining-experience-t416416/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/624f504bd15e7.jpeg/99.jpg"
  },
  {
    "order": 48,
    "provincia": "tarragona",
    "city": "cambrils",
    "categoria": "sea",
    "categoriaLabel": "Water Park",
    "titulo": "Costa Daurada: Cambrils Inflatable Water Park",
    "descripcion": "Bounce, slide and splash across a giant floating obstacle course right on the sea — pure summer fun.",
    "precio": 18,
    "precioDisplay": "18€ - 25€",
    "rating": 4.4,
    "trending": false,
    "keywords": "cambrils inflatable water park floating obstacle course sea aqua park kids costa daurada",
    "etiquetaPie": "Family",
    "url": "https://www.getyourguide.com/cambrils-l91400/costa-dorada-cambrils-inflatable-water-park-t1345237/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/fef12fa1c933b87b552989e51c51838dc8a6e6d7c47da83798b9ad726dc527ee.png/99.jpg"
  },
  {
    "order": 49,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "tours",
    "categoriaLabel": "Family",
    "titulo": "Salou: Minigolf Pass with Gear",
    "descripcion": "A relaxed round of minigolf with all the gear included — a perfect easygoing plan for families.",
    "precio": 10,
    "precioDisplay": "10€ - 15€",
    "rating": 4.4,
    "trending": false,
    "keywords": "salou minigolf pass gear family kids game course fun costa daurada",
    "etiquetaPie": "Family",
    "url": "https://www.getyourguide.com/salou-l1884/salou-minigolf-pass-with-gear-t937964/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/f0ad294cd196fcd599e4c53ec74f02994b4bf5306749fceda184735462ef4202.jpg/99.jpg"
  },
  {
    "order": 50,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "tours",
    "categoriaLabel": "Transport",
    "titulo": "Salou–Cambrils: Round-Trip Ferry",
    "descripcion": "Hop between Salou and Cambrils by sea on a scenic round-trip ferry — a breezy alternative to the road.",
    "precio": 16,
    "precioDisplay": "16€ - 22€",
    "rating": 4.5,
    "trending": false,
    "keywords": "salou cambrils round trip ferry boat transfer sea coast scenic costa daurada",
    "etiquetaPie": "Scenic",
    "url": "https://www.getyourguide.com/salou-l1884/cambrils-salou-salou-cambrils-round-trip-ferry-t221310/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/0af92e15abc865ea.jpeg/99.jpg"
  },
  {
    "order": 51,
    "provincia": "tarragona",
    "city": "cambrils",
    "categoria": "culture",
    "categoriaLabel": "Nature & Gardens",
    "titulo": "Cambrils: Parc Samà Entry Ticket",
    "descripcion": "Wander the palm-lined paths, lakes and follies of this romantic 19th-century colonial garden near Cambrils.",
    "precio": 12,
    "precioDisplay": "12€ - 16€",
    "rating": 4.6,
    "trending": false,
    "keywords": "cambrils parc sama romantic garden park nature lake modernist costa daurada",
    "etiquetaPie": "Nature",
    "url": "https://www.getyourguide.com/cambrils-l91400/cambrils-parc-sama-entry-ticket-t399540/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/60a639a471d28.jpeg/99.jpg"
  },
  {
    "order": 52,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Nightlife",
    "titulo": "Barcelona: The Original Barcelona Boat Party",
    "descripcion": "Board this party boat and admire beautiful views of the Barcelona coastline as you dance to the beats of the onboard DJ. Get your pre-game on with drinks vouchers…",
    "precio": 59,
    "precioDisplay": "From 59€",
    "rating": 4,
    "trending": true,
    "keywords": "barcelona: the original barcelona boat party barcelona food",
    "etiquetaPie": "Boat Party",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-the-original-barcelona-boat-party-t84906/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/eb9ebe4603257d51c60e319102b0af4c1412c27ecef72058a1f2f84e1be4f94e.jpg/99.jpg"
  },
  {
    "order": 53,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Catamaran Party Cruise with BBQ Meal",
    "descripcion": "Climb aboard a catamaran and get the party started with your friends. Enjoy music and dancing as you cruise along the coast of Barcelona. Feast from a barbecue meal…",
    "precio": 50,
    "precioDisplay": "From 50€",
    "rating": 4.3,
    "trending": false,
    "keywords": "barcelona: catamaran party cruise with bbq meal barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-catamaran-party-cruise-with-bbq-meal-t147204/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/6fbccc87ca2e246f.jpeg/99.jpg"
  },
  {
    "order": 54,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Speakeasy Crawl, Hidden Bars with Optional Tapas",
    "descripcion": "Leave the busy tourist areas behind and discover Barcelona's hidden nightlife on a guided Speakeasy Crawl. Visit secret cocktail bars, stylish hidden spots, and…",
    "precio": 20,
    "precioDisplay": "From 20€",
    "rating": 4.6,
    "trending": false,
    "keywords": "barcelona: speakeasy crawl, hidden bars with optional tapas barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-speakeasy-explore-hidden-bars-with-tapas-t170032/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/e4417ea60f18075602ddf69b5e7c4974b5baa0e8bed54e27632a9ba2e0cc7d34.png/99.jpg"
  },
  {
    "order": 55,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Hidden Barcelona Tapas Tour: Wine, Fun & Local Secrets",
    "descripcion": "Food Lover Tour Explores Barcelona the local way, after dark, one bar at a time. This evening tapas crawl is all about great food and the stories behind the bars…",
    "precio": 74,
    "precioDisplay": "From 74€",
    "rating": 4.9,
    "trending": false,
    "keywords": "hidden barcelona tapas tour: wine, fun & local secrets barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-tapas-crawl-full-meal-drinks-all-included-t333276/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3b0642eb6620afee552ab01bdc741d338fc01e40e4837280a947661efcd4a03c.jpg/99.jpg"
  },
  {
    "order": 56,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Beach Club with Pool Party & Open Air Club",
    "descripcion": "Make a splash at Barcelona’s wildest pool party! This Beach Club turns into a sun-soaked paradise with 1,000 party lovers, epic music, 4 drinks, and unforgettable…",
    "precio": 59,
    "precioDisplay": "From 59€",
    "rating": 3.5,
    "trending": false,
    "keywords": "barcelona: beach club with pool party & open air club barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-beach-club-pool-party-with-dj-t839587/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/0514aff64ff73c42c6f31b2fedb141858e46eb3f9e130f52fa7195d8a14cf317.jpg/99.jpg"
  },
  {
    "order": 57,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Tipsy Tapas & History Tour in the Gothic Quarter",
    "descripcion": "Enjoy traditional tapas and iconic Spanish drinks as you explore the hidden gems of Barcelona’s Gothic Quarter on a guided walking tour. An immersive experience…",
    "precio": 79,
    "precioDisplay": "From 79€",
    "rating": 4.7,
    "trending": false,
    "keywords": "barcelona: tipsy tapas & history tour in the gothic quarter barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-tipsy-tapas-history-tour-in-the-gothic-quarter-t890438/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/a40668e8d7602b40b6e9c43a5b205046939f42aa549a9ba4058178dc4641d9a9.jpeg/99.jpg"
  },
  {
    "order": 58,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: AFTERWORK Catamaran Cruise w/ Music & Drinks",
    "descripcion": "Sail off into the sunset and watch the magic unfold on a catamaran cruise in Barcelona. Enjoy a glass of wine and an enjoy the music or local DJ playing live music.",
    "precio": 25,
    "precioDisplay": "From 25€",
    "rating": 4.7,
    "trending": false,
    "keywords": "barcelona: afterwork catamaran cruise w/ music & drinks barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-afterwork-catamaran-cruise-w-music-drinks-t928143/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/8c45fb10ab665781e4bef3ea00244d2e288521fede85dd4dc943172fab6a848a.jpg/99.jpg"
  },
  {
    "order": 59,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Nightlife",
    "titulo": "Barcelona Top Night Club Experience + VIP Club Entry",
    "descripcion": "Experience Barcelonna ultimate club crawl!!Party challenges, and VIP entry. Meet new people and party hard until sunrise!",
    "precio": 20,
    "precioDisplay": "From 20€",
    "rating": 3.9,
    "trending": true,
    "keywords": "barcelona top night club experience + vip club entry barcelona food",
    "etiquetaPie": "VIP Club",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-top-night-club-experience-vip-club-entry-t1082881/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/8129a4197a201fd1a7d422fd6bcb157846e50698e041143ae848625a4eb4d4a6.jpeg/99.jpg"
  },
  {
    "order": 60,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona Party Night Tour Bars & VIP Club Pass",
    "descripcion": "Get ready to dive into the most happening unforgetable night in the heart of Barcelona on this tour. Explore the liveliest neighborhoods,Exclusive access, and…",
    "precio": 16,
    "precioDisplay": "From 16€",
    "rating": 4.1,
    "trending": false,
    "keywords": "barcelona party night tour bars & vip club pass barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-night-walking-tour-bars-vip-club-pass-t1125011/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/7056a69020f575ae40be3986ca22de8166b998a07074f4c83cb03bb1c5429aae.jpeg/99.jpg"
  },
  {
    "order": 61,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Bar Crawl at Gaixample",
    "descripcion": "Experience Barcelona’s vibrant LGBTQ culture on this small-group bar crawl through Gaixample. It can be difficult for first-time visitors to navigate the city’s…",
    "precio": 30,
    "precioDisplay": "From 30€",
    "rating": 4.8,
    "trending": false,
    "keywords": "barcelona: bar crawl at gaixample barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-bar-crawl-at-gaixample-t1138649/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/fc72f62b6ead4f7ee0f5ef4294a8cd5f6610a01485ea50be045fd96c52d6dd59.jpeg/99.jpg"
  },
  {
    "order": 62,
    "provincia": "barcelona",
    "city": "sitges",
    "categoria": "food",
    "categoriaLabel": "Nightlife",
    "titulo": "Barcelona Party Bus & After VIP club entry",
    "descripcion": "Come and live an unforgettable experience aboard a \"Barcelona party bus\" Enjoy welcome drink, pre-parties, and priority entry to top nightclubs for an unforgettable…",
    "precio": 55,
    "precioDisplay": "From 55€",
    "rating": 5,
    "trending": false,
    "keywords": "barcelona party bus & after vip club entry sitges food",
    "etiquetaPie": "Party Bus",
    "url": "https://www.getyourguide.com/sitges-l1769/barcelona-sitges-carnival-party-bus-t1184893/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/cdeebc05b567b99e40adf162951b46d4ec917ff11e76701ce8d44762bddc5cec.png/99.jpg"
  },
  {
    "order": 63,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona Nightlife Experience: Karaoke, Dance & Local Guide",
    "descripcion": "Discover Barcelona's nightlife with local guides, enjoy karaoke, meet travelers from around the world, and experience a fun social evening.",
    "precio": 16,
    "precioDisplay": "From 16€",
    "rating": 4.8,
    "trending": false,
    "keywords": "barcelona nightlife experience: karaoke, dance & local guide barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/buzz-barcelona-beach-club-white-party-t1219232/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3a111652fabd0647b403dbd7863f1d658c07f96e523c948dbf1c15c2a938b3fb.png/99.jpg"
  },
  {
    "order": 64,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Nightlife",
    "titulo": "Barcelona Boat Party (Thu, Fri, Sat & Sun) + Nightlife Tour",
    "descripcion": "Experience Barcelona's famous boat party, then keep the night going with a guided nightlife tour through some of the city's liveliest venues.",
    "precio": 75,
    "precioDisplay": "From 75€",
    "rating": 5,
    "trending": false,
    "keywords": "barcelona boat party (thu, fri, sat & sun) + nightlife tour barcelona food",
    "etiquetaPie": "Rooftop & Boat",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-buzz-summer-package-full-moon-rooftop-boat-t1220933/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/7af0e889d6c4c65de77be54f8037fc0bc80db12bccda4274c8c2e2a7647bdb6b.jpeg/99.jpg"
  },
  {
    "order": 65,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Sangria & Cocktail Making Class with Tapas",
    "descripcion": "Learn to make traditional Spanish sangria and cocktails in a fun mixology class in Barcelona. Enjoy your creations with tasty tapas while discovering the secrets…",
    "precio": 42,
    "precioDisplay": "From 42€",
    "rating": 5,
    "trending": false,
    "keywords": "barcelona: sangria & cocktail making class with tapas barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-sangria-cocktail-making-class-with-tapas-t1255110/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/08b1b76e676c0cdef49ae1e52471a30f0551ba0a572272e57537ae5af5326d53.png/99.jpg"
  },
  {
    "order": 66,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Experience Authentic Barcelona Nightlife with a Local DJ",
    "descripcion": "Explore Barcelona’s nightlife with a local DJ who knows the scene. Discover exclusive bars, meet interesting people, and end the night dancing in one of the city’s…",
    "precio": 39,
    "precioDisplay": "From 39€",
    "rating": 5,
    "trending": false,
    "keywords": "experience authentic barcelona nightlife with a local dj barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-nightlife-tour-with-local-dj-dance-floor-t1258142/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3a8fd769ddfaba158c08faa1b9f473c8686daebf52d002bbac4d3c5364518162.png/99.jpg"
  },
  {
    "order": 67,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Pubcrawl with VIP entry to Rooftop and Nightclubs",
    "descripcion": "✅EXPERIENCE THE LEGENDARY NIGHTLIFE Ready for an unforgettable night in Barcelona? Next Experience takes you on an exciting adventure. Music, dancing, and partying",
    "precio": 31,
    "precioDisplay": "From 31€",
    "rating": 4.4,
    "trending": false,
    "keywords": "barcelona: pubcrawl with vip entry to rooftop and nightclubs barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-rooftop-bars-and-nightclubs-tour-t1262639/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/a35b4642627e1c62994345bd53803ed1f99aeb93f440595b27e79b85a5e83558.jpg/99.jpg"
  },
  {
    "order": 68,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona: Icebar Experience at the Beach + 1 Drink",
    "descripcion": "Chill out at Icebarcelona, the ultimate icebar experience. Sip cocktails in ice glasses, marvel at stunning ice sculptures, vibe to great music, or watch the sunset…",
    "precio": 19,
    "precioDisplay": "From 19€",
    "rating": 4.1,
    "trending": false,
    "keywords": "barcelona: icebar experience at the beach + 1 drink barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/the-ice-bar-experience-at-icebarcelona-t157464/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/01ebc1421a7e557c6939f8baba1509b9ff6cecf0150f86cd89500d3a7f923e6d.jpeg/99.jpg"
  },
  {
    "order": 69,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Intimate Flamenco Show El Duende Bar & Cocktails Barcelona",
    "descripcion": "Discover our signature cocktail menu while enjoying an intimate flamenco show in central Barcelona, backed by the 55-year legacy of the renowned Tablao Flamenco…",
    "precio": 25,
    "precioDisplay": "From 25€",
    "rating": 4.7,
    "trending": false,
    "keywords": "intimate flamenco show el duende bar & cocktails barcelona barcelona food",
    "etiquetaPie": "Live Show",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-flamenco-show-with-drink-at-la-rambla-t629660/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/fb1568bcef2ed2fb7dd95d1a8968119ed1f2db5046eef8978f31bd7eebf11e9b.jpg/99.jpg"
  },
  {
    "order": 70,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Barcelona: City Sights Electric Quad Tour",
    "descripcion": "Discover Barcelona's highlights on a electric quad tour that takes to you areas like La Rambla. Enjoy a tour that is priced per quad, allowing the driver and…",
    "precio": 79,
    "precioDisplay": "From 79€",
    "rating": 4.5,
    "trending": false,
    "keywords": "barcelona: city sights electric quad tour barcelona sea",
    "etiquetaPie": "Adventure",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-city-sights-electric-quad-tour-t711046/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/1ced477f80d52f0655fa7c77b8160e5083dacdc97236ce0c652336311f4f081f.jpg/99.jpg"
  },
  {
    "order": 71,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Barcelona Jetski: Jetski Rental without a License",
    "descripcion": "Enjoy a thrilling experience riding a jet ski without needing a license. Souvenir photos included",
    "precio": 60,
    "precioDisplay": "From 60€",
    "rating": 4.5,
    "trending": false,
    "keywords": "barcelona jetski: jetski rental without a license barcelona sea",
    "etiquetaPie": "Water Sports",
    "url": "https://www.getyourguide.com/barcelona-l45/mataro-unlicensed-jet-ski-rental-at-the-port-of-mataro-t1299826/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/a8a665a964a28543e933c1d73de5c37e39d220302db31312638dec650c498506.jpg/99.jpg"
  },
  {
    "order": 72,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Barcelona Gotic Tour with BEST BARS and KISSING WALL",
    "descripcion": "All just a kiss away Will you find love? Begin at the iconic Cathedral, wander the Gothic Quarter, discover the Kiss Mural, enjoy rooftop views, hidden bars…",
    "precio": 22,
    "precioDisplay": "From 22€",
    "rating": 5,
    "trending": false,
    "keywords": "barcelona gotic tour with best bars and kissing wall barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/barcelona-magical-gothic-quarter-kisses-hidden-bars-tour-t1310822/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3fb7eaba6338a4ca8e6eb8aad0b3eb543ca5cd7bec56979b2a4357e5b8f3bfa6.png/99.jpg"
  },
  {
    "order": 73,
    "provincia": "barcelona",
    "city": "barcelona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Exclusive Underground: Raval by Night with Dinner and Drinks",
    "descripcion": "Discover the hidden soul of Barcelona on a guided tour of El Raval. Enjoy a sunset drink on a rooftop terrace, savor a 3-course dinner, and visit a hidden bar for…",
    "precio": 185,
    "precioDisplay": "From 185€",
    "rating": 0,
    "trending": false,
    "keywords": "exclusive underground: raval by night with dinner and drinks barcelona food",
    "etiquetaPie": "Nightlife",
    "url": "https://www.getyourguide.com/barcelona-l45/exclusive-underground-raval-by-night-with-dinner-and-drinks-t1320452/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/9939a1ee875dc1667b8f20ec5d38af1e42621fa266e641d7fee356229d8cc951.png/99.jpg"
  },
  {
    "order": 74,
    "provincia": "girona",
    "city": "girona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Girona: Game of Thrones Small Group Tour",
    "descripcion": "Immerse yourself in the atmosphere of Braavos and King's landing and stroll through the narrow streets of the medieval and Jewish Girona. Discover the filming…",
    "precio": 32,
    "precioDisplay": "From 32€",
    "rating": 4.9,
    "trending": false,
    "keywords": "girona: game of thrones small group tour girona culture",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/girona-l550/girona-game-of-thrones-small-group-tour-t149528/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/64b8d9d03121d.jpeg/99.jpg"
  },
  {
    "order": 75,
    "provincia": "girona",
    "city": "girona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Girona: Small Group Walking Tour",
    "descripcion": "Join an extensive tour to discover the monumental city of Girona. Feel transported to the medieval ages while strolling around its Jewish quarter. Explore 2,000…",
    "precio": 32,
    "precioDisplay": "From 32€",
    "rating": 4.8,
    "trending": false,
    "keywords": "girona: small group walking tour girona culture",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/girona-l550/girona-small-group-walking-tour-t151013/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5aaf7c6803c1c.jpeg/99.jpg"
  },
  {
    "order": 76,
    "provincia": "girona",
    "city": "girona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Girona: Jewish Heritage Guided City Tour and Museum Visit",
    "descripcion": "Discover the Girona's Jewish Quarter, one of the best-preserved from the Middle Ages in Europe. Enjoy a guided visit to the Museum of Jewish History, the last…",
    "precio": 45,
    "precioDisplay": "From 45€",
    "rating": 4.9,
    "trending": false,
    "keywords": "girona: jewish heritage guided city tour and museum visit girona culture",
    "etiquetaPie": "Skip the Line",
    "url": "https://www.getyourguide.com/girona-l550/girona-jewish-heritage-guided-city-tour-and-museum-visit-t309788/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5d9865d0bc0d2.jpeg/99.jpg"
  },
  {
    "order": 77,
    "provincia": "girona",
    "city": "girona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Girona: Cathedral of Girona + Art Museum + St. Felix Church",
    "descripcion": "Visit 3 of Girona's highlights with this 3-in-1 pass that includes entry to the Girona Art Museum, Girona Cathedral, and the Church of St. Felix.",
    "precio": 12,
    "precioDisplay": "From 12€",
    "rating": 4.5,
    "trending": false,
    "keywords": "girona: cathedral of girona + art museum + st. felix church girona culture",
    "etiquetaPie": "Skip the Line",
    "url": "https://www.getyourguide.com/girona-l550/girona-art-museum-cathedral-st-felix-church-3-in-1-pass-t407669/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/618a8d417755b.jpeg/99.jpg"
  },
  {
    "order": 78,
    "provincia": "girona",
    "city": "girona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Girona: Museum of Cinema Entry Ticket",
    "descripcion": "Go on a journey through 500 years of cinematic history with this entry ticket to the Museum of Cinema. Discover the origins, background, and art of cinema, with…",
    "precio": 7,
    "precioDisplay": "From 7€",
    "rating": 4.6,
    "trending": false,
    "keywords": "girona: museum of cinema entry ticket girona culture",
    "etiquetaPie": "Skip the Line",
    "url": "https://www.getyourguide.com/girona-l550/girona-museum-of-cinema-entry-ticket-t419114/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/eca8b2278119954aa002fd957c78c5fcb6cab6f7d2ebedf78cc010e580380e7b.jpg/99.jpg"
  },
  {
    "order": 79,
    "provincia": "girona",
    "city": "figueres",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Figueres: Dalí Theatre-Museum Entry Ticket",
    "descripcion": "Explore the mind of Salvador Dalí at the Dalí Theatre-Museum in Figueres. Discover the largest collection of his works, including paintings, sculptures, and…",
    "precio": 23,
    "precioDisplay": "From 23€",
    "rating": 4.7,
    "trending": false,
    "keywords": "figueres: dalí theatre-museum entry ticket figueres culture",
    "etiquetaPie": "Skip the Line",
    "url": "https://www.getyourguide.com/figueres-l4723/figueres-dali-theatre-museum-entry-ticket-t831886/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/48b6d10e063825e3951bc9d4cec1a2eb71ffb43611a7eac7cd35018a10324eb4.jpeg/99.jpg"
  },
  {
    "order": 80,
    "provincia": "girona",
    "city": "lloret-de-mar",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Lloret de Mar: Catamaran Sailing Cruise with BBQ and Drinks",
    "descripcion": "Set sail on a catamaran along the stunning Costa Brava on this cruise from Lloret de Mar. Swim in crystal waters and soak up some sun while listening to music…",
    "precio": 50,
    "precioDisplay": "From 50€",
    "rating": 4.5,
    "trending": false,
    "keywords": "lloret de mar: catamaran sailing cruise with bbq and drinks lloret-de-mar sea",
    "etiquetaPie": "Boat Trip",
    "url": "https://www.getyourguide.com/lloret-de-mar-l2322/lloret-de-mar-catamaran-sailing-cruise-with-bbq-and-drinks-t215928/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3bb15824b34fe491.jpeg/99.jpg"
  },
  {
    "order": 81,
    "provincia": "girona",
    "city": "l-estartit",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "From L’Estartit: Snorkeling Trip to the Medes Islands",
    "descripcion": "Explore the underwater world of the Medes Islands Natural Marine Reserve on a snorkeling trip from L’Estartit. Enjoy swimming and sunbathing, as well as a cruise…",
    "precio": 38,
    "precioDisplay": "From 38€",
    "rating": 4.5,
    "trending": false,
    "keywords": "from l’estartit: snorkeling trip to the medes islands l-estartit sea",
    "etiquetaPie": "Water Sports",
    "url": "https://www.getyourguide.com/l-estartit-l91403/from-l-estartit-3-hour-snorkeling-trip-to-the-medes-islands-t220695/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5c8f8dd5334e3.jpeg/99.jpg"
  },
  {
    "order": 82,
    "provincia": "girona",
    "city": "lloret-de-mar",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "From Lloret de Mar: Roundtrip Ferry to Tossa de Mar",
    "descripcion": "Hop on board a ferry and sail along the Costa Brava between Lloret de Mar and Tossa de Mar. Hop off the boat and explore or relax on the beach and enjoy the warm…",
    "precio": 33,
    "precioDisplay": "From 33€",
    "rating": 4.6,
    "trending": false,
    "keywords": "from lloret de mar: roundtrip ferry to tossa de mar lloret-de-mar sea",
    "etiquetaPie": "Boat Trip",
    "url": "https://www.getyourguide.com/lloret-de-mar-l2322/from-lloret-de-mar-roundtrip-ferry-to-tossa-de-mar-t222411/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/5c91244a0fb1f.jpeg/99.jpg"
  },
  {
    "order": 83,
    "provincia": "girona",
    "city": "sant-feliu-de-guixols",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Costa Brava: Sea Caves Kayaking and Snorkeling Tour",
    "descripcion": "Discover the wild coast of Costa Brava. Join a guided kayaking and snorkeling tour in a small group, exploring coves, caves, channels, cliffs, and islands in…",
    "precio": 34,
    "precioDisplay": "From 34€",
    "rating": 4.8,
    "trending": false,
    "keywords": "costa brava: sea caves kayaking and snorkeling tour sant-feliu-de-guixols sea",
    "etiquetaPie": "Water Sports",
    "url": "https://www.getyourguide.com/sant-feliu-de-guixols-l98145/costa-brava-sea-caves-kayaking-and-snorkeling-tour-t396079/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/75e3355eacd6bc91.jpeg/99.jpg"
  },
  {
    "order": 84,
    "provincia": "girona",
    "city": "roses",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "From Roses: Cruise on Costa Brava to Cadaqués",
    "descripcion": "Enjoy a boat trip with onboard commentary and sail along Costa Brava from Roses to the fishing village of Cadaqués. Stop in the village to discover picturesque…",
    "precio": 27,
    "precioDisplay": "From 27€",
    "rating": 4.4,
    "trending": false,
    "keywords": "from roses: cruise on costa brava to cadaqués roses sea",
    "etiquetaPie": "Boat Trip",
    "url": "https://www.getyourguide.com/roses-spain-l92004/from-roses-cruise-on-costa-brava-to-cadaques-t425645/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/475f1434a9e9337203729cf0672f153311c08ad4692cd24eaa182f656adaea10.png/99.jpg"
  },
  {
    "order": 85,
    "provincia": "girona",
    "city": "tossa-de-mar",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Tossa de Mar: Guided Kayaking Tour & Snorkelling",
    "descripcion": "Enjoy a guided kayaking tour with a guide in Tossa de Mar. Explore the Costa Brava, snorkel, enter caves, and admire the views of local fauna and flora.",
    "precio": 45,
    "precioDisplay": "From 45€",
    "rating": 4.9,
    "trending": false,
    "keywords": "tossa de mar: guided kayaking tour & snorkelling tossa-de-mar sea",
    "etiquetaPie": "Water Sports",
    "url": "https://www.getyourguide.com/tossa-de-mar-l90930/tossa-de-mar-guided-kayaking-tour-snorkelling-t475482/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/6489bbab10323.jpeg/99.jpg"
  },
  {
    "order": 86,
    "provincia": "girona",
    "city": "palamos",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Palamós: Sunset Boat Tour with Glass of Cava",
    "descripcion": "Explore the beauty of the Costa Brava on a boat trip from Palamós to Calella de Palafrugell. Enjoy the bar service and taste the Palamós red shrimp with a glass of…",
    "precio": 40,
    "precioDisplay": "From 40€",
    "rating": 4.4,
    "trending": false,
    "keywords": "palamós: sunset boat tour with glass of cava palamos sea",
    "etiquetaPie": "Boat Trip",
    "url": "https://www.getyourguide.com/palamos-l1751/palamos-sunset-boat-tour-with-glass-of-cava-t546141/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/897bba754bfb8de5.jpeg/99.jpg"
  },
  {
    "order": 87,
    "provincia": "girona",
    "city": "lloret-de-mar",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Sailboat day with BBQ on the Costa Brava",
    "descripcion": "Sail along the Costa Brava with a group of up to 11 people. Enjoy the sea, stop for a swim, and have a barbecue on board. You just have to come and relax.",
    "precio": 2000,
    "precioDisplay": "From 2000€",
    "rating": 0,
    "trending": false,
    "keywords": "sailboat day with bbq on the costa brava lloret-de-mar sea",
    "etiquetaPie": "Boat Trip",
    "url": "https://www.getyourguide.com/lloret-de-mar-l2322/sailboat-day-with-bbq-on-the-costa-brava-t1170725/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/7aaa8ce4db82634e55d50bfa16ec67ce1525108fef5ff90982c2e4d5b7587d4a.jpg/99.jpg"
  },
  {
    "order": 88,
    "provincia": "girona",
    "city": "lloret-de-mar",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Lloret de Mar: Sunset Catamaran Cruise with DJ and Drinks",
    "descripcion": "Embark on an evening sailboat ride departing from Lloret de Mar and take in the beachside landscapes of the Costa Brava. Get the party started with drinks and live…",
    "precio": 35,
    "precioDisplay": "From 35€",
    "rating": 4.7,
    "trending": false,
    "keywords": "lloret de mar: sunset catamaran cruise with dj and drinks lloret-de-mar food",
    "etiquetaPie": "Boat Party",
    "url": "https://www.getyourguide.com/lloret-de-mar-l2322/lloret-de-mar-sunset-catamaran-cruise-with-dj-and-drinks-t427417/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/7a1b59e8feb04b7c0b51b991af5289906d129170b2ecf78cc65fd74254c20e99.jpeg/99.jpg"
  },
  {
    "order": 89,
    "provincia": "girona",
    "city": "blanes",
    "categoria": "tours",
    "categoriaLabel": "Tour",
    "titulo": "Blanes: Marimurtra Botanical Garden Entry Ticket",
    "descripcion": "Spend the day exploring the Marimurtra Botanical Garden. Take in panoramic views of the Mediterranean and learn about the thousands of plant species that call this…",
    "precio": 10,
    "precioDisplay": "From 10€",
    "rating": 4.7,
    "trending": false,
    "keywords": "blanes: marimurtra botanical garden entry ticket blanes tours",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/blanes-l96850/costa-brava-marimurtra-botanical-garden-entry-ticket-t412981/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/ba5fdab533fe22cd.jpeg/99.jpg"
  },
  {
    "order": 90,
    "provincia": "girona",
    "city": "girona",
    "categoria": "tours",
    "categoriaLabel": "Tour",
    "titulo": "Olot: Espai Cràter Volcanology Center Entry Ticket",
    "descripcion": "Discover the world of volcanology with tickets to the Espai Cràter: the only place where you can learn about volcanoes from inside a volcano!",
    "precio": 8,
    "precioDisplay": "From 8€",
    "rating": 4.5,
    "trending": false,
    "keywords": "olot: espai cràter volcanology center entry ticket girona tours",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/girona-l550/girona-espai-crater-volcanology-center-entry-ticket-t431485/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/44d4026244fb6d50a318768962e163d7be46c5ec549c3a2cd3bbca78c317c7bf.png/99.jpg"
  },
  {
    "order": 91,
    "provincia": "girona",
    "city": "peratallada",
    "categoria": "tours",
    "categoriaLabel": "Tour",
    "titulo": "Bike Tour to Medieval Villages in Costa Brava",
    "descripcion": "Explore the medieval heart of Empordà on a guided bike tour. Ride through scenic countryside, discover charming villages, and learn about the region's history from…",
    "precio": 89,
    "precioDisplay": "From 89€",
    "rating": 5,
    "trending": false,
    "keywords": "bike tour to medieval villages in costa brava peratallada tours",
    "etiquetaPie": "Bike Tour",
    "url": "https://www.getyourguide.com/peratallada-l147462/scenic-bike-tour-to-medieval-villages-in-costa-brava-t1204455/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/425cbae0ada9bb3aa2d4097f039be5d4a53baf93c053e5b28a3d47e93e62dc62.jpg/99.jpg"
  },
  {
    "order": 92,
    "provincia": "girona",
    "city": "tossa-de-mar",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Vintage 4x4 Tour Costa Brava :Lloret de Mar & Hidden Gems",
    "descripcion": "Explore Lloret de Mar in a unique way aboard a vintage Land Rover. Discover scenic viewpoints, historic sites, and hidden spots along the beautiful Costa Brava.",
    "precio": 35,
    "precioDisplay": "From 35€",
    "rating": 4.9,
    "trending": false,
    "keywords": "vintage 4x4 tour costa brava :lloret de mar & hidden gems tossa-de-mar sea",
    "etiquetaPie": "Adventure",
    "url": "https://www.getyourguide.com/tossa-de-mar-l90930/lloret-de-mar-guided-sightseeing-tour-in-a-4x4-vehicle-t680690/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/791eebcff461ea544ead68c5febf355ba49e663414008c6fc56f8224a19211df.jpeg/99.jpg"
  },
  {
    "order": 93,
    "provincia": "girona",
    "city": "girona",
    "categoria": "food",
    "categoriaLabel": "Food & Nightlife",
    "titulo": "Girona Evening Food Tour & Tapas Bar Experience",
    "descripcion": "The best way to discover the city, its flavours and its nightlife! Join us for a funny, original and tasty evening Food Tour in the beautiful city of Girona.",
    "precio": 90,
    "precioDisplay": "From 90€",
    "rating": 4.9,
    "trending": false,
    "keywords": "girona evening food tour & tapas bar experience girona food",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/girona-l550/girona-evening-food-tour-tapas-bar-experience-t590538/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/476c4b360a580a92868127458ea3b3cf96dfc31aced20dc3d1132ef7420257d7.png/99.jpg"
  },
  {
    "order": 94,
    "provincia": "girona",
    "city": "tossa-de-mar",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Tossa de Mar Secret Coves & Hidden Caves Exclusive Experience",
    "descripcion": "Aboard a zodiac, in a small group, we will sail towards Tossa de Mar to admire the historic old town, the coves, and gorgeous caves, then we will stop for a swim…",
    "precio": 59,
    "precioDisplay": "From 59€",
    "rating": 4.7,
    "trending": false,
    "keywords": "tossa de mar secret coves & hidden caves exclusive experience tossa-de-mar sea",
    "etiquetaPie": "Boat Trip",
    "url": "https://www.getyourguide.com/tossa-de-mar-l90930/tossa-de-mar-boat-excursion-in-the-calanques-of-the-costa-brava-t1044479/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/ced07b99bb114637cbb2feba10299abd1c7d8b0084feaaa186f257b20bb1def2.jpg/99.jpg"
  },
  {
    "order": 95,
    "provincia": "girona",
    "city": "girona",
    "categoria": "culture",
    "categoriaLabel": "Culture",
    "titulo": "Girona: Old Town Walking Tour with Local Guide",
    "descripcion": "Explore Girona's Old Town on a guided walking tour. Discover hidden stories, local secrets, and the city's history as you wander through medieval streets and cross…",
    "precio": 80,
    "precioDisplay": "From 80€",
    "rating": 0,
    "trending": false,
    "keywords": "girona: old town walking tour with local guide girona culture",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/girona-l550/girona-old-town-walking-tour-with-local-guide-t1316529/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/e1842494b35e42cc4ef4b391ab6b2065fa6ef97a3a06b46a99bdf91544bede12.jpg/99.jpg"
  },
  {
    "order": 96,
    "provincia": "lleida",
    "city": "vielha",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "4×4 sightseeing tour in Valle d'Aran - Wildlife, flora, and alpine landscapes",
    "descripcion": "4x4 or 4WD TOURS in the Aran Valley, Ribagorça, and Pallars. Discover secret alpine film locations. Themed outings for wildlife and flora spotting and trekking…",
    "precio": 135,
    "precioDisplay": "From 135€",
    "rating": 5,
    "trending": false,
    "keywords": "4×4 sightseeing tour in valle d'aran - wildlife, flora, and alpine landscapes vielha sea",
    "etiquetaPie": "Adventure",
    "url": "https://www.getyourguide.com/vielha-l218675/4x4-sightseeing-tour-in-valle-d-aran-wildlife-flora-and-alpine-landscapes-t838426/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/3c9104274a1c04d5bddea745e6251a588cb11599b0e889d12ad1eb17d7704b64.jpeg/99.jpg"
  },
  {
    "order": 97,
    "provincia": "lleida",
    "city": "baqueira",
    "categoria": "tours",
    "categoriaLabel": "Tour",
    "titulo": "Private Ski Lessons in Baqueira Beret",
    "descripcion": "Private ski lessons tailored to you, to help you improve your technique or get to know the resort",
    "precio": 70,
    "precioDisplay": "From 70€",
    "rating": 0,
    "trending": false,
    "keywords": "private ski lessons in baqueira beret baqueira tours",
    "etiquetaPie": "Mountain",
    "url": "https://www.getyourguide.com/baqueira-l186124/private-ski-lessons-in-baqueira-beret-t1003663/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/d1bd1120bf37a1a5b01d0c557c12abc43f0ebe4743352d7788ea75f31e7f88f1.jpg/99.jpg"
  },
  {
    "order": 98,
    "provincia": "lleida",
    "city": "lleida",
    "categoria": "tours",
    "categoriaLabel": "Tour",
    "titulo": "Lleida: Llacs Cycling Route",
    "descripcion": "Cycle along the first cycling route in Lleida. We take care of the bikes and the logistics!",
    "precio": 60,
    "precioDisplay": "From 60€",
    "rating": 0,
    "trending": false,
    "keywords": "lleida: llacs cycling route lleida tours",
    "etiquetaPie": "Guided Tour",
    "url": "https://www.getyourguide.com/lleida-l100032/lleida-llacs-cycling-route-t1057236/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/4fdb0b87a136ae3ab807396ae7a5e22771f2ef7ef6098ee55c2f1d58b65f418a.jpg/99.jpg"
  },
  {
    "order": 99,
    "provincia": "lleida",
    "city": "lleida",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Les: Garonne River Rafting Trip with Guide & Equipment",
    "descripcion": "Experience the thrill of rafting on the Garonne River in the Aran Valley. Navigate the Les–Pont de Rei section with a certified guide and enjoy a safe adventure…",
    "precio": 44,
    "precioDisplay": "From 44€",
    "rating": 0,
    "trending": false,
    "keywords": "les: garonne river rafting trip with guide & equipment lleida sea",
    "etiquetaPie": "Adventure",
    "url": "https://www.getyourguide.com/lleida-l100032/les-garonne-river-rafting-trip-with-guide-equipment-t1380382/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/ae6c94345cbc23354c967b9545cd2ec838bcdba05477f0c4e743ddb310eebbae.jpg/99.jpg"
  },
  {
    "order": 100,
    "provincia": "lleida",
    "city": "lleida",
    "categoria": "sea",
    "categoriaLabel": "Sea & Adventure",
    "titulo": "Aigüestortes National Park: Guided Hike with Waterfall",
    "descripcion": "Explore the Gerdar Fir Forest on a guided hike in Aigüestortes National Park. Discover the area's flora, fauna, and natural history, and reach the Gerber Waterfall…",
    "precio": 125,
    "precioDisplay": "From 125€",
    "rating": 0,
    "trending": false,
    "keywords": "aigüestortes national park: guided hike with waterfall lleida sea",
    "etiquetaPie": "Hiking",
    "url": "https://www.getyourguide.com/lleida-l100032/aiguestortes-national-park-guided-hike-with-waterfall-t1397540/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/48f01746e64d888bc5bd076d6e950136a766aa67810f784b1f75ce9d21ed5789.jpeg/99.jpg"
  },
  {
    "order": 101,
    "provincia": "tarragona",
    "city": "salou",
    "categoria": "food",
    "categoriaLabel": "Nightlife",
    "titulo": "Salou: Bingo Bangas Party Night with Drinks",
    "descripcion": "Join a bingo party night with a twist. Sing, dance, and cheer to the best tunes with a DJ and host. Enjoy all-inclusive drinks and win exciting prizes.",
    "precio": 41,
    "precioDisplay": "From 41€",
    "rating": 4.4,
    "trending": false,
    "keywords": "salou: bingo bangas party night with drinks salou food",
    "etiquetaPie": "Party Night",
    "url": "https://www.getyourguide.com/salou-l1884/salou-bingo-bangas-party-night-with-drinks-t1084504/?partner_id=IBO5PAK&utm_medium=local_partners",
    "imagen": "https://cdn.getyourguide.com/img/tour/8b4401615f6cbc81f4e7b3f6d9bb95fcff10c9cfc7d141927be6fdcde788ca30.jpg/99.jpg"
  }
];
